name: Check Base-Branch [PR]
on: [ pull_request, pull_request_target, pull_request_review_comment, pull_request_review ]
jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
        - if:  == 'refs/heads/dev' || github.head_ref == 'refs/heads/dev'
          name: Check base-branch(dev) - master=>next (FORCE)
          uses: dezren39/check-base-branch-action@v2
          with:
            protected-branches: "main"
            default-branch: "next"
            update-branch: true
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
        - if: github.ref == 'refs/heads/next' || github.head_ref == 'refs/heads/next'
          name: Check base-branch(next) - dev=>main
          uses: dezren39/check-base-branch-action@v2
          with:
            protected-branches: "dev"
            default-branch: "main"
            update-branch: false
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
        - if: github.ref == 'refs/heads/main' || github.head_ref == 'refs/heads/main'
          name: Check base-branch(main) - next=>dev
          uses: dezren39/check-base-branch-action@v2
          with:
            protected-branches: "next"
            default-branch: "dev"
            update-branch: false
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
        - if: github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/next' && github.ref != 'refs/heads/main' && github.head_ref != 'refs/heads/dev'  && github.head_ref != 'refs/heads/next' && github.head_ref != 'refs/heads/main'
          name: Check base-branch(feature) - main,next=>dev (FORCE)
          uses: dezren39/check-base-branch-action@v2
          with:
            protected-branches: "main,next"
            default-branch: "dev"
            update-branch: true
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
