name: Check PR Base-Branch
on: [pull_request]
jobs:     
  check-pr-base-branch:
    runs-on: ubuntu-latest
    steps:
      - if: github.ref == 'refs/heads/main'
        name: Check PR base branch - main
        uses: a-b-r-o-w-n/check-base-branch-action@v1
        with:
          protectedBranches: "next"
          defaultBranch: "dev"
          update-branch: false
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - if: github.ref == 'refs/heads/next'
        name: Check PR base branch - next
        uses: a-b-r-o-w-n/check-base-branch-action@v1
        with:
          protectedBranches: "dev"
          defaultBranch: "main"
          update-branch: false
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - if: github.ref == 'refs/heads/dev'
        name: Check PR base branch - dev
        uses: a-b-r-o-w-n/check-base-branch-action@v1
        with:
          protectedBranches: "main"
          defaultBranch: "next"
          update-branch: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - if: ! ('refs/heads/dev' || 'refs/heads/next' || 'refs/heads/main')
        name: Check PR base branch - feature(unprotected)
        uses: a-b-r-o-w-n/check-base-branch-action@v1
        with:
          protectedBranches: "main, next"
          defaultBranch: "dev"
          update-branch: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
