name: Install, Build, Test [node]
on: [push, pull_request, pull_request_target, create, fork, release]
jobs:
  install-build-test_node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '12', '10' ]
        pm: [ 'yarn', 'npm' ]
    name: Install, Build, Test - ${{ matrix.pm }}(${{ matrix.node }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Install dependencies
        run: ${{ matrix.pm }} install #--immutable --immutable-cache --check-cache
      - name: Build target
        run: ${{ matrix.pm }} build
      - name: Test code
        run: ${{ matrix.pm }} test
