on:
  push:
    branches:
      - "main"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'dev'
          commit_message_template: 'chore(backmerge) [Automated] [skip ci] Merged {source_ref} into target {target_branch}'
