name: Install, Build, Test [@nodejs]
on: [push, pull_request, pull_request_target, create, fork, release]
jobs:
  install-build-test_node:
    name: Install, Build, Test - ${{ matrix.pm }}(${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '12', '10' ]
        pm: [ 'yarn', 'npm' ]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Install dependencies
        run: ${{ matrix.pm }} install #--immutable --immutable-cache --check-cache
      - name: Build target
        run: ${{ matrix.pm }} build
      - name: Test code
        run: ${{ matrix.pm }} test
