name: Base Merger [pr]
on:
  issue_comment:
    types: [created]
jobs:
  base-merger_update:
    name: Base Merger - Update
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/update')
    runs-on: ubuntu-latest
    steps:
    - name: Base merger - update
      uses: junmo-kim/base-merger@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
