# Author: Drewry Pope
# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/
name: Release (DRY-RUN) [@github][@nodejs][@npm]
on: [push, pull_request, pull_request_target, create, fork, release]
jobs:
  release_dry-run:
    name: Release (DRY-RUN) - yarn(${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Install dependencies
        run: yarn install #--immutable --immutable-cache --check-cache
      - name: Build target
        run: yarn build
      - name: Test code
        run: yarn test
      - name: DRY-RUN Release package	
        env:	
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}	
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}	
        run: npx semantic-release --dry-run
 
